[book]
title = "zkbook cheat sheet"
description = ""
authors = ["ChengYueJia"]
language = "en"
multilingual = false
src = "src"


[output.html]
mathjax-support = true
curly-quotes = true
no-section-label = true
git-repository-url = "https://github.com/ChengYueJia/zkbook-notes"
git-repository-icon = "fa-github"

[output.html.print]
page-break = true

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true
level = 3

# output pdf
#[output.pdf]


